### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aaaaaa2493** [moevm/mse_voice_acting_of_activity_on_the_github#58]
Exception in thread Download events:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:/GitHub/mse_voice_acting_of_activity_on_the_github/src/backend.py", line 51, in download_events
    last_event = new_events[0]
IndexError: list index out of range

**Comment by aaaaaa2493** [comment]
Exception in thread Download events:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:/GitHub/mse_voice_acting_of_activity_on_the_github/src/backend.py", line 64, in download_events
    print(f'{event_queue[-1].created_at.time()}-'
IndexError: list index out of range
